# -*- coding: utf-8 -*-
"""ML.RF_RS

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1e_KbSqTJrUHc-Ms11bcJYHCon8366XkY
"""

import pandas as pd       #  reading and handling data
import numpy as np        #  math operations
import matplotlib.pyplot as plt  #  graphs
import seaborn as sns     #  graphs

print("Libraries loaded ✅")

from google.colab import files
uploaded = files.upload()

df = pd.read_csv('AI MODEL - Sheet1.csv')
df.head()  # Show first 5 rows

df.shape   # (rows, columns)
df.info()  # Data types & missing values

df.isnull().sum()

plt.figure(figsize=(15, 6))
plt.plot(df['ch1_voltage'], label='Channel 1')
plt.plot(df['ch2_voltage'], label='Channel 2')
plt.plot(df['ch3_voltage'], label='Channel 3')
plt.legend()
plt.title("EMG Signals from 3 Channels")
plt.xlabel("Time (Samples)")
plt.ylabel("Signal Amplitude")
plt.show()

from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

df = df.dropna()

X = df[['ch1_voltage', 'ch2_voltage', 'ch3_voltage']]  # EMG signals
y = df['label']  # Gesture: 1 (rest), 2 (fist)

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

model = RandomForestClassifier(n_estimators=100, random_state=42)
model.fit(X_train, y_train)

y_pred = model.predict(X_test)
print("Accuracy:", accuracy_score(y_test, y_pred))
print("Confusion Matrix:\n", confusion_matrix(y_test, y_pred))
print("Report:\n", classification_report(y_test, y_pred))

# Example EMG reading
new_data = [[0.42, 0.31, 0.27]]
gesture = model.predict(new_data)
print("Predicted Gesture:", "Fist" if gesture[0]==2 else "Rest")

import joblib
joblib.dump(model, 'emg_gesture_model.pkl')

model = joblib.load('emg_gesture_model.pkl')



# Example EMG reading
new_data = [[0.48, 0.33, 0.29]]
gesture = model.predict(new_data)
print("Predicted Gesture:", "Fist" if gesture[0]==2 else "Rest")